version: '3.8'
services:
  node-elevate:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node-elevate
    entrypoint: sh -c 'npm install && npm run start:dev'
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    ports:
      - ${PORT}:${PORT}
    networks:
      - node-elevate-net

networks:
  node-elevate-net:
